### PR TITLE
Implemented packaging using CPack and generation of the pkg-config file

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by karel-burda** [comment]
Hi, sorry, missed this PR since it was not assigned to me.

Thanks a lot, in any case!

Is this PR stiall actual?

**Comment by KOLANICH** [comment]
Why shouldn't it be actual?

**Comment by karel-burda** [comment]
> Why shouldn't it be actual?

Becauase I was offline for some time and realized that there's PR only after a few days. But it's great that it's actual, thanks a lot for this update!

Can we please fix 3 things in this MR?

1) Raise a version in the `CMakeLists.txt` and also in the `README.md`
2) Fix tiny formatting issues (e.g. match the indentation of the newly added changes in the `CMakeListst.txt` with the existing code; remove whitespace in the https://github.com/karel-burda/function-loader/pull/21/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR118)
3) Re-target destination branch to the `develop`

Thanks a lot!

Then I'll merge it and later merge to `master`.

**Comment by karel-burda** [comment]
And it seems that the CI fails, e.g. Linux `CMake Error at CMakeLists.txt:109 (install):
  install DIRECTORY given no DESTINATION!`. Can we please look also on this?

**Comment by KOLANICH** [comment]
Should be OK by now. I have also replaced the pkg-config generator with a better one.

**Review by karel-burda — APPROVED** [review]
Thanks a lot for this contribution.

**Pull request merged**
